new_type = DynamicFormsEngine::DynamicFormType.new(
  {name: "Tenant  Application", description: "Complete applications are time sensitive with priority given to those with earnest money deposits. When your application is complete please submit it. Any questions please e-mail applications@sfrent.net", uuid: nil, user_id: 1, form_type: "Multi-step", is_public: false}
)
new_type.fields.build([
  {field_order: 0, name: "Personal Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 1, name: "First Name: ", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 2, name: "Last Name:", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 117, name: "Do you have any water filled furniture or do you intend to get any water filled furniture?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 118, name: "Have you filed for bankruptcy in the past 10 years?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 119, name: "Have you ever been evicted or have you ever refused to pay rent for any reason?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 36, name: "Current Address:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 120, name: "Have you, or do you intend to , posses, sell or use illicit drugs or narcotics in your residence?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 70, name: "Start Date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 41, name: "Years Resided:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 3, name: "Mobile Phone Number", field_type: "phone_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 4, name: "Secondary Phone Number:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 5, name: "Work number", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 23, name: "Apartment Size:", field_type: "options_select", required: false, content_meta: "SRO, 1 bedroom, Studio", included_in_report: false, field_width: "6"},
  {field_order: 44, name: "Monthly rent:", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 7, name: "Social Security:", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 8, name: "Driver License #:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 9, name: "Date of birth:", field_type: "calendar", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 6, name: "Email address:", field_type: "email_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 10, name: "Other names used:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 11, name: "EMERGENCY CONTACT INFO", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 12, name: "First Name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 13, name: "Last Name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 39, name: "State:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 14, name: "Relationship:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 15, name: "Phone:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 16, name: "Email:", field_type: "email_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 61, name: "Employment History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 42, name: "Landlords name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 68, name: "Country", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 74, name: "Gross monthly salary:", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 65, name: "Company address:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 21, name: "Apartment", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 22, name: "Building:", field_type: "options_select", required: false, content_meta: "Claridge", included_in_report: false, field_width: "6"},
  {field_order: 80, name: "City:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 136, name: "Explanation:", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 38, name: "City:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 45, name: "Reason for leaving:", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 46, name: "Move in date:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 35, name: "Rental History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 47, name: "Move out date:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 40, name: "Zip:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 25, name: "Estimated Move In Date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 26, name: "Other persons to occupy Premises(Each adult occupant must submit a separate application)", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 27, name: "First Name: ", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 122, name: "If any of the questions above answered yes, please explain:", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 125, name: "Agreement", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 126, name: "Earnest Money of ", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 114, name: "Adding a pet will increase the base rent : Dog $100 Cat $50", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 48, name: "Prior residence(If previous less than 5 years)", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 56, name: "Landlords phone:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 57, name: "Monthly rent:", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 58, name: "Reason for leaving", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 116, name: "Do you have any civil judgment been entered against you in the past 10 years?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 87, name: "Attach pay stub #1:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 62, name: "", field_type: "long_description", required: false, content_meta: "<u>If applicant is self-employed, then we will need the following:</u> If a sole propriertor, then, Form 1040 pages 1 &2 plus schedule(s) C for the most recent year filled. if a corporation,  A LLC, Partnership, Limited Partnership or any other separate entity on which self-employment income is being evaluated, then the entire return for the most recent year filled.None of the documents provided will be returned, so you may wish to send copies. If currently a student, please complete Student Information section", included_in_report: false, field_width: "12"},
  {field_order: 123, name: "How did you hear about this vacancy?", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 72, name: "Supervisor name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 124, name: "What made you decide to apply with us?", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 66, name: "City:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 67, name: "State:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 73, name: "Supervisor phone:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 63, name: "Current Employer:", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 86, name: "Gross monthly salary", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 75, name: "Attach pay stub #1:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 71, name: "End Date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 91, name: "Name of Institution:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 104, name: "Weigth:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 105, name: "Gender:", field_type: "options_select", required: false, content_meta: "Male, Female", included_in_report: false, field_width: "6"},
  {field_order: 107, name: "Type:", field_type: "options_select_with_other", required: false, content_meta: "Dog, Cat,Other", included_in_report: false, field_width: "12"},
  {field_order: 108, name: "Breed:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 109, name: "Color:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 110, name: "Weight:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 128, name: "", field_type: "long_description", required: false, content_meta: "Applicant agrees that Applicant will participate in Lanlord's mandatory Electronic Funds Transfer (EFT) program for rent payment, and before taking possession of the premises will grant Landlord and/or his agent(s) the necessary authorization to enroll Applicant in the program.", included_in_report: false, field_width: "12"},
  {field_order: 111, name: "Gender:", field_type: "options_select", required: false, content_meta: "Male, Female", included_in_report: false, field_width: "6"},
  {field_order: 106, name: "Picture:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 112, name: "Picture:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 113, name: "Do you intent to get any pets?", field_type: "options_select", required: false, content_meta: "Yes, No", included_in_report: false, field_width: "12"},
  {field_order: 115, name: "Verifications", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 64, name: "Current Employer name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 129, name: "", field_type: "long_description", required: false, content_meta: "Applicant represents all information contained in this APPLICATION to be true and accurate and understands that owner/manager will rely upon said information when accepting this Application. Applicant hereby  authorizes the owner/manager and his employees and agents to verify said information and make independent investigations to determine Applicant's credit, financial and character standing, which will include a credit and criminal background check. Applicant hereby releases owner/manager, his employees and agents and any firm or person supplying them with information form any liability whatsoever concerning the release or use of this information and will hold them all harmless form any suit or reprisal whatsoever. All holders of any such information are hereby authorized to release any and all such information they may have concerning Applicant.", included_in_report: false, field_width: "12"},
  {field_order: 132, name: "Miscellanenous ", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 133, name: "Please upload any financial supporting documents if receiving financial aid or any other income", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 135, name: "File Upload #2:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 69, name: "Position:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 102, name: "Breed:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 54, name: "Years Resided:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 77, name: "Prior Company", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 79, name: "Company address:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 78, name: "Company Name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 121, name: "Have you ever lived here before or do you know anyone living here now or in the past?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "6"},
  {field_order: 81, name: "State:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 28, name: "Last Name: ", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 29, name: "Age", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 30, name: "Relationship to Applicant", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 31, name: "First Name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 32, name: "Last Name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 34, name: "Relationship to Applicant", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 33, name: "Age:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 37, name: "Street Address #2:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 49, name: "Street address:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 50, name: "Street address #2:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 51, name: "City:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 52, name: "State:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 53, name: "Zip:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 43, name: "Landlords phone:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 55, name: "Landlords name:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 59, name: "Move in date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 60, name: "Move out date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 24, name: "If you are interested in a specific unit number enter it", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 82, name: "Start date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 83, name: "End date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 84, name: "Supervisor name", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 85, name: "Supervisor phone", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 89, name: "Student Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 76, name: "Attach pay Stub #2:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 88, name: "Attach pay stub #2:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 92, name: "Address of Institution:", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 93, name: "Start date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 94, name: "Expected end date:", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 95, name: "Course of study:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 96, name: "Degree sought:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 97, name: "Registrar Contact Name if any:", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 98, name: "Registar Main Tel #:", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 99, name: "Pet Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 100, name: "Do you have a pet?", field_type: "options_select", required: false, content_meta: "Yes,No", included_in_report: false, field_width: "12"},
  {field_order: 103, name: "Color:", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 101, name: "Type:", field_type: "options_select_with_other", required: false, content_meta: "Dog, Cat, Bird, Other,Other", included_in_report: false, field_width: "12"},
  {field_order: 134, name: "File upload #1:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 130, name: "By checking here and enterting your name below, I declare under penalty of perjury that the foregoing is true and correct", field_type: "agreement", required: true, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 131, name: "Full Name:", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 17, name: "Bank Info", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 18, name: "Please list the total amount of your liquid assets", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "12"},
  {field_order: 19, name: "Bank Statement #1:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 20, name: "Bank Statement #2:", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  {field_order: 127, name: "", field_type: "long_description", required: false, content_meta: "Is hereby given as surety for Applicant's promise to timely complete the Lease Application, and execute the Lease within 24 hours after notification of acceptance. It is specifically understood that the Earnest money is fully refundable if Lanlord/PIP/sfrent.net rejects the application and offer. Applicant understands and agrees that Landlord/PIP/sfrent.net will deposit the earnest money payment upon receipt and that if the applicant is rejected, Landlord/PIP/sfrent.net will not issue the refund until (10) business days have elapsed from the date of Landlord/PIP/sfrent.net deposit of the Earnest Money payment. The earnest money may be applied to part of the security deposit at execution of the Lease and payment of the move-in money. If Lanlord/PIP/sfrent.net ahs duly accepted this Application and offer, it is then treated as a completed contract to rent/lease the above described property and Applicant's attempted revocation shall be deemed a breach of contract. PLEASE NOTE: If this application and offer is revoked by Applicant for any reason, the Applicant shall forfeit the entire Earnest Money. Applicant and Landlord agree that the Earnest Money deposit represents a fair and reasonable estimate of the costs and damages that Landlord will sustain as a result of payment represents a liquidated damage for breach of promise by Applicant. Failure to provide application details requested in this application within 48 hours of initial submission may be considered, at Landlord/PIP/sfrent.net's discretion, as a revocation. Applicant furthere acknowledges that where a unit is available for immediate move-in, Applicant lease date will begin no later than twenty-four (24) hours from the time and date on which Applicant has been notified that Applicant's application has been approved.", included_in_report: false, field_width: "12"},
  {field_order: 90, name: "Registered students must provide a letter, on institution letterhead, confirming registration", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"}
])

new_type.save!