tenant_app = DynamicFormsEngine::DynamicFormType.new(
	{name: "Tenant Application", description: "Complete applications are time sensitive with priority given to those with earnest money deposits. When your application is complete please submit it. Any questions please e-mail applications@sfrent.net", uuid: nil, user_id: 3, form_type: "Multi-step", is_public: false},
)
tenant_app.fields.build([
	{ field_order: 0, name: "Personal Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 1, name: "First Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 2, name: "Last Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 135, name: "Do you have any water filled furniture or do you intend to get any water filled furniture?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 136, name: "Have you filed for bankruptcy in the past 10 years?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 137, name: "Have you ever been evicted or have you ever refused to pay rent for any reason?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 39, name: "Current Address", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 138, name: "Have you, or do you intend to , posses, sell or use illicit drugs or narcotics in your residence?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 75, name: "Start Date", field_type: "calendar", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 45, name: "Years Resided", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 3, name: "Mobile Phone Number", field_type: "phone_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 4, name: "Secondary Phone Number", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 5, name: "Work number", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 26, name: "Apartment Size", field_type: "options_select", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 48, name: "Monthly rent", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 7, name: "Social Security", field_type: "social_security", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 9, name: "Driver License #", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 8, name: "Date of birth", field_type: "date_select", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 6, name: "Email address", field_type: "email_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 12, name: "Other names used", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 13, name: "EMERGENCY CONTACT INFO", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 14, name: "Emergency First Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 15, name: "Emergency Last Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 42, name: "State", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 16, name: "Relationship", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 17, name: "Emergency Phone", field_type: "phone_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 18, name: "Emergency Email", field_type: "email_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 65, name: "Employment History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 46, name: "Landlords name", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 73, name: "Country", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 78, name: "Gross monthly salary", field_type: "currency", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 69, name: "Company address", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 24, name: "Apartment", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 25, name: "Building", field_type: "options_select", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 84, name: "City #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 156, name: "Explanation", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 41, name: "City", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 51, name: "Reason for leaving(if applicable)", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 49, name: "Move in date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 38, name: "Rental History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 50, name: "Move out date(if applicable)", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 43, name: "Zip", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 28, name: "Estimated Move In Date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 29, name: "Other persons to occupy Premises(Each adult occupant must submit a separate application)", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 30, name: "First Name #1", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 140, name: "If any of the questions above answered yes, please explain", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 143, name: "Agreement", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 144, name: "Earnest Money of ", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 52, name: "Prior residence(If previous less than 5 years)", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 60, name: "Landlords phone #2", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 61, name: "Monthly rent #2", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 64, name: "Reason for leaving #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 134, name: "Do you have any civil judgment been entered against you in the past 10 years?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 94, name: "Attach secondary pay stub #1", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 66, name: "", field_type: "long_description", required: false, content_meta: "<u>If applicant is self-employed, then we will need the following:</u> If a sole propriertor, then, Form 1040 pages 1 &2 plus schedule(s) C for the most recent year filled. if a corporation,  A LLC, Partnership, Limited Partnership or any other separate entity on which self-employment income is being evaluated, then the entire return for the most recent year filled.None of the documents provided will be returned, so you may wish to send copies. If currently a student, please complete Student Information section", included_in_report: false, field_width: "12"},
	{ field_order: 141, name: "How did you hear about this vacancy?", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 76, name: "Supervisor name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 142, name: "What made you decide to apply with us?", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 70, name: "City", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 71, name: "State", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 77, name: "Supervisor phone", field_type: "phone_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 67, name: "Current Employer:", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 93, name: "Gross monthly salary #2", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 79, name: "Attach pay stub #1", field_type: "file_upload", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 98, name: "Name of Institution", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 113, name: "Weigth", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 114, name: "Gender", field_type: "options_select", required: false, content_meta: "Male, Female", included_in_report: false, field_width: "6"},
	{ field_order: 118, name: "Type #2", field_type: "options_select_with_other", required: false, content_meta: "Dog,Cat,Other", included_in_report: false, field_width: "12"},
	{ field_order: 119, name: "Breed #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 120, name: "Color #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 121, name: "Weight #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 146, name: "", field_type: "long_description", required: false, content_meta: "Applicant agrees that Applicant will participate in Lanlord's mandatory Electronic Funds Transfer (EFT) program for rent payment, and before taking possession of the premises will grant Landlord and/or his agent(s) the necessary authorization to enroll Applicant in the program.", included_in_report: false, field_width: "12"},
	{ field_order: 122, name: "Gender #2", field_type: "options_select", required: false, content_meta: "Male, Female", included_in_report: false, field_width: "6"},
	{ field_order: 115, name: "Picture", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 123, name: "Picture #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 133, name: "Verification", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 68, name: "Current Employer name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 147, name: "", field_type: "long_description", required: false, content_meta: "Applicant represents all information contained in this APPLICATION to be true and accurate and understands that owner/manager will rely upon said information when accepting this Application. Applicant hereby  authorizes the owner/manager and his employees and agents to verify said information and make independent investigations to determine Applicant's credit, financial and character standing, which will include a credit and criminal background check. Applicant hereby releases owner/manager, his employees and agents and any firm or person supplying them with information form any liability whatsoever concerning the release or use of this information and will hold them all harmless form any suit or reprisal whatsoever. All holders of any such information are hereby authorized to release any and all such information they may have concerning Applicant.", included_in_report: false, field_width: "12"},
	{ field_order: 150, name: "Miscellaneous ", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 151, name: "Please upload any financial supporting documents if receiving financial aid or any other income", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 153, name: "File Upload #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 74, name: "Position", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 111, name: "Breed", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 58, name: "Years Resided #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 81, name: "Prior Company", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 83, name: "Company address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 82, name: "Company Name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 139, name: "Have you ever lived here before or do you know anyone living here now or in the past?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 85, name: "State #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 31, name: "Last Name #1", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 32, name: "Age #1", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 33, name: "Relationship to Applicant #1", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 34, name: "First Name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 35, name: "Last Name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 37, name: "Relationship to Applicant #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 36, name: "Age #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 40, name: "Secondary Address", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 53, name: "Street address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 54, name: "Secondary address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 55, name: "City #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 56, name: "State #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 57, name: "Zip #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 47, name: "Landlords phone", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 59, name: "Landlords name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 62, name: "Move in date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 63, name: "Move out date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 27, name: "If you are interested in a specific unit number enter it", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 89, name: "Start date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 90, name: "End date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 91, name: "Supervisor name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 92, name: "Supervisor phone #2", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 96, name: "Student Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 80, name: "Attach pay Stub #2", field_type: "file_upload", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 95, name: "Attach secondary pay stub #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 99, name: "Address of Institution", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 100, name: "Start date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 101, name: "Expected end date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 102, name: "Course of study", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 103, name: "Degree sought", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 104, name: "Registrar Contact Name if any", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 105, name: "Registrar Main Tel #", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 107, name: "Pet Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 108, name: "Do you have a pet?", field_type: "options_select", required: true, content_meta: "Yes,No", included_in_report: false, field_width: "12"},
	{ field_order: 112, name: "Color", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 110, name: "Type", field_type: "options_select_with_other", required: false, content_meta: "Dog,Cat,Bird,Other", included_in_report: false, field_width: "12"},
	{ field_order: 152, name: "File upload #1", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 149, name: "By checking here and enterting your name below, I declare under penalty of perjury that the foregoing is true and correct", field_type: "agreement", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 148, name: "[Enter Full Name]", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 19, name: "Bank Info", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 20, name: "Please list the total amount of your liquid assets", field_type: "currency", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 22, name: "Bank Statement #1", field_type: "file_upload", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 23, name: "Bank Statement #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 145, name: "", field_type: "long_description", required: false, content_meta: "Is hereby given as surety for Applicant's promise to timely complete the Lease Application, and execute the Lease within 24 hours after notification of acceptance. It is specifically understood that the Earnest money is fully refundable if Lanlord/PIP/sfrent.net rejects the application and offer. Applicant understands and agrees that Landlord/PIP/sfrent.net will deposit the earnest money payment upon receipt and that if the applicant is rejected, Landlord/PIP/sfrent.net will not issue the refund until (10) business days have elapsed from the date of Landlord/PIP/sfrent.net deposit of the Earnest Money payment. The earnest money may be applied to part of the security deposit at execution of the Lease and payment of the move-in money. If Lanlord/PIP/sfrent.net ahs duly accepted this Application and offer, it is then treated as a completed contract to rent/lease the above described property and Applicant's attempted revocation shall be deemed a breach of contract. PLEASE NOTE: If this application and offer is revoked by Applicant for any reason, the Applicant shall forfeit the entire Earnest Money. Applicant and Landlord agree that the Earnest Money deposit represents a fair and reasonable estimate of the costs and damages that Landlord will sustain as a result of payment represents a liquidated damage for breach of promise by Applicant. Failure to provide application details requested in this application within 48 hours of initial submission may be considered, at Landlord/PIP/sfrent.net's discretion, as a revocation. Applicant furthere acknowledges that where a unit is available for immediate move-in, Applicant lease date will begin no later than twenty-four (24) hours from the time and date on which Applicant has been notified that Applicant's application has been approved.", included_in_report: false, field_width: "12"},
	{ field_order: 97, name: "Registered students must provide a letter, on institution letterhead, confirming registration", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 10, name: "Driver License State", field_type: "options_select_with_us_states", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 11, name: "If driver license state other than U.S. enter country", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 72, name: "Zip Code", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 86, name: "Zip Code #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 109, name: "Pet #1", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 117, name: "Pet #2", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 126, name: "Type #3", field_type: "options_select_with_other", required: false, content_meta: "Dog,Cat,Bird,Fish,Other", included_in_report: false, field_width: "12"},
	{ field_order: 127, name: "Breed #3", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 128, name: "Color #3", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 129, name: "Weight #3", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 130, name: "Gender #3", field_type: "options_select", required: false, content_meta: "Male, Female", included_in_report: false, field_width: "6"},
	{ field_order: 131, name: "Picture #3", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 125, name: "Pet #3", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 116, name: "Pet Documentation", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 124, name: "Pet Documentation #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 132, name: "Pet Documentation #3", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 154, name: "File Upload #3", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 155, name: "File Upload #4", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 87, name: "Country #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 88, name: "Position #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 21, name: "Please upload a recent bank statement(s)", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 106, name: "School Document", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
  	{ field_order: 44, name: "Current ownership", field_type: "options_select", required: false, content_meta: "Rent,Lease,Own", included_in_report: false, field_width: "6"},
])

tenant_app.save!

guarantor_app = DynamicFormsEngine::DynamicFormType.new(
	{name: "Guarantor Application ", description: "This application is being made by the undersigned for the express purpose as a Personal Guarantor. When your application is complete please submit it. Any questions please e-mail applications@sfrent.net", uuid: nil, user_id: 3, form_type: "Multi-step", is_public: false}
)
guarantor_app.fields.build([
	{ field_order: 0, name: "Personal Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 1, name: "Tenant Applicant Info", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 2, name: "Tenant First Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 3, name: "Tenant Last Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 19, name: "Housing History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 20, name: "Current Address", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 21, name: "Secondary Address", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 4, name: "Building", field_type: "options_select", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 5, name: "Apartment Size", field_type: "options_select", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 6, name: "Guarantor Info", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 7, name: "First Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 8, name: "Last Name", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 9, name: "Mobile Phone Number", field_type: "phone_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 10, name: "Secondary Phone Number", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 13, name: "Social Security", field_type: "social_security", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 14, name: "Date of birth", field_type: "date_select", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 15, name: "Driver License #", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 16, name: "Driver License State", field_type: "options_select_with_us_states", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 17, name: "If driver license state other than U.S. enter country", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 18, name: "Other names used", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 11, name: "Work number", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 12, name: "Email address", field_type: "email_validation", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 22, name: "City", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 23, name: "State", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 24, name: "Zip", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 26, name: "If current renting form Landlord", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 27, name: "Landlord name", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 28, name: "Landlord phone", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 29, name: "Monthly rent/mortgage", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 30, name: "Total household occupants", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 33, name: "Reason for leaving(If applicable)", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 31, name: "Move in date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 32, name: "Move out date(If applicable)", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 34, name: "Prior residence ", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 35, name: "Street address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 36, name: "Secondary address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 37, name: "City #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 38, name: "State #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 39, name: "Zip #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 41, name: "If previous residence was from Landlord", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 42, name: "Landlords name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 43, name: "Landlords phone #2", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 44, name: "Monthly rent/mortgage #2", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 45, name: "Total household occupants #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 48, name: "Reason for leaving #2", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 46, name: "Move in Date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 47, name: "Move out date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 49, name: "Employment History", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 50, name: "", field_type: "long_description", required: false, content_meta: "<u>If applicant is self-employed, then we will need the following:</u>  If a sole propriertor, then, Form 1040 pages 1 &2 plus schedule(s) C for the most recent year filled. if a corporation, A LLC, Partnership, Limited Partnership or any other separate entity on which self-employment income is being evaluated, then the entire return for the most recent year filled.None of the documents provided will be returned, so you may wish to send copies. If currently a student, please complete Student Information section", included_in_report: false, field_width: "12"},
	{ field_order: 51, name: "Current Employer", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 52, name: "Current Employer name", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 53, name: "Company address", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 54, name: "City", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 55, name: "State", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 56, name: "Zip Code", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 57, name: "Country", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 58, name: "Position", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 59, name: "Start date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 60, name: "Supervisor name", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 61, name: "Supervisor phone", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 62, name: "Gross monthly salary", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 63, name: "Attach pay stub #1", field_type: "file_upload", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 64, name: "Attach pay stub #2", field_type: "file_upload", required: true, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 65, name: "Prior Company", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 66, name: "Company Name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 67, name: "Company address #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 68, name: "City #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 69, name: "State #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 70, name: "Zip code #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "4"},
	{ field_order: 71, name: "Country #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 72, name: "Position #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 73, name: "Start date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 74, name: "End date #2", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 75, name: "Supervisor name #2", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 76, name: "Supervisor phone #2", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 77, name: "Gross monthly salary #2", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 78, name: "Attach secondary pay stub #1", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 79, name: "Attach secondary pay stub #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 80, name: "Student Info", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 81, name: "Registered students must provide a letter, on institution letterhead, confirming registration", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 82, name: "Name of Institution", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 83, name: "Address of Institution", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 84, name: "Start date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 85, name: "Expected end date", field_type: "calendar", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 86, name: "Course of study", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 87, name: "Degree sought", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 88, name: "Registrar Contact Name if any", field_type: "text_field", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 89, name: "Registrar Main Tel #", field_type: "phone_validation", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 91, name: "Verification", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 92, name: "Do you have any civil judgment been entered against you in the past 10 years?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 93, name: "Have you filed for bankruptcy in the past 10 years?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 94, name: "Have you ever been evicted or have you ever refused to pay rent for any reason?", field_type: "options_select", required: true, content_meta: "No,Yes", included_in_report: false, field_width: "6"},
	{ field_order: 95, name: "If any of the questions above answered yes, please explain", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 96, name: "Agreement", field_type: "field_group", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 97, name: "Earnest money of", field_type: "currency", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 98, name: "", field_type: "long_description", required: false, content_meta: "Is hereby given as surety for Applicant's promise to timely complete the Lease Application, and execute the Lease within 24 hours after notification of acceptance. It is specifically understood that the Earnest money is fully refundable if Lanlord/PIP/sfrent.net rejects the application and offer. Applicant understands and agrees that Landlord/PIP/sfrent.net will deposit the earnest money payment upon receipt and that if the applicant is rejected, Landlord/PIP/sfrent.net will not issue the refund until (10) business days have elapsed from the date of Landlord/PIP/sfrent.net deposit of the Earnest Money payment. The earnest money may be applied to part of the security deposit at execution of the Lease and payment of the move-in money. If Lanlord/PIP/sfrent.net ahs duly accepted this Application and offer, it is then treated as a completed contract to rent/lease the above described property and Applicant's attempted revocation shall be deemed a breach of contract. PLEASE NOTE: If this application and offer is revoked by Applicant for any reason, the Applicant shall forfeit the entire Earnest Money. Applicant and Landlord agree that the Earnest Money deposit represents a fair and reasonable estimate of the costs and damages that Landlord will sustain as a result of payment represents a liquidated damage for breach of promise by Applicant. Failure to provide application details requested in this application within 48 hours of initial submission may be considered, at Landlord/PIP/sfrent.net's discretion, as a revocation. Applicant furthere acknowledges that where a unit is available for immediate move-in, Applicant lease date will begin no later than twenty-four (24) hours from the time and date on which Applicant has been notified that Applicant's application has been approved.", included_in_report: false, field_width: "12"},
	{ field_order: 99, name: "", field_type: "long_description", required: false, content_meta: "Applicant agrees that Applicant will participate in Lanlord's mandatory Electronic Funds Transfer (EFT) program for rent payment, and before taking possession of the premises will grant Landlord and/or his agent(s) the necessary authorization to enroll Applicant in the program.", included_in_report: false, field_width: "12"},
	{ field_order: 100, name: "", field_type: "long_description", required: false, content_meta: "\r\nApplicant represents all information contained in this APPLICATION to be true and accurate and understands that owner/manager will rely upon said information when accepting this Application. Applicant hereby authorizes the owner/manager and his employees and agents to verify said information and make independent investigations to determine Applicant's credit, financial and character standing, which will include a credit and criminal background check. Applicant hereby releases owner/manager, his employees and agents and any firm or person supplying them with information form any liability whatsoever concerning the release or use of this information and will hold them all harmless form any suit or reprisal whatsoever. All holders of any such information are hereby authorized to release any and all such information they may have concerning Applicant.", included_in_report: false, field_width: "12"},
	{ field_order: 101, name: "[enter full name]", field_type: "text_field", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 102, name: "By checking here and enterting your name below, i declare under penalty of perjury that the foregoing is true and correct", field_type: "agreement", required: true, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 103, name: "Miscellaneous", field_type: "small_header", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 104, name: "Please upload any other supportive documents", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 105, name: "File upload #1", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 106, name: "File Upload #2", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 107, name: "Provide any additional information we should know or that may help us make a decision about your application", field_type: "short_description", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 108, name: "Explanation", field_type: "text_area", required: false, content_meta: "", included_in_report: false, field_width: "12"},
	{ field_order: 90, name: "School document", field_type: "file_upload", required: false, content_meta: "", included_in_report: false, field_width: "6"},
	{ field_order: 25, name: "Current ownership", field_type: "options_select", required: false, content_meta: "Rent,Lease,Own", included_in_report: false, field_width: "6"},
	{ field_order: 40, name: "Previous ownership #2", field_type: "options_select", required: false, content_meta: "Rent,Lease,Own", included_in_report: false, field_width: "6"}
])

guarantor_app.save!